"""Add detailed project fields

Revision ID: 376d7767e119
Revises: 
Create Date: 2025-11-28 22:04:44.515328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376d7767e119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section2_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('section2_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('section2_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('section3_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('section3_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('section3_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('features_grid', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('accordion_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('stats_bar', sa.JSON(), nullable=True))
        batch_op.alter_column('detailed_description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('detailed_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('stats_bar')
        batch_op.drop_column('accordion_items')
        batch_op.drop_column('features_grid')
        batch_op.drop_column('section3_image')
        batch_op.drop_column('section3_text')
        batch_op.drop_column('section3_title')
        batch_op.drop_column('section2_image')
        batch_op.drop_column('section2_text')
        batch_op.drop_column('section2_title')

    # ### end Alembic commands ###
